flowchart BT
    A{"Facility 1"} -- |LocatedIn_BFO0000171| --> B{"City 1"}
    B -- |LocatedIn_BFO0000171| --> C{"State 1"}
    A -- |rdf:type| --> D("object BFO_0000030")
    B -- |rdf:type| --> E("fiat object part BFO_0000024")
    C -- |rdf:type| --> E

    style A fill:#E1BEE7,stroke:#E1BEE7
    style B fill:#E1BEE7,stroke:#E1BEE7
    style C stroke:#E1BEE7,fill:#E1BEE7
    style D stroke:#FFE0B2,fill:#FFE0B2
    style E stroke:#FFE0B2,fill:#FFE0B2