flowchart BT
   A{"Facility 1"} -- |LocatedIn_BFO0000171| --> B{"City 1"}
    B -- |LocatedIn_BFO0000171| --> C{"State 1"}
    A -- |rdf:type| --> D("facility")
    B -- |rdf:type| --> E("site BFO_0000029")
    C -- |rdf:type| --> E
    A -- |rdfs:label| --> F['Empire State Building']
    B -- |rdfs:label| --> G['New York City']
    C -- |rdfs:label| --> H['New York State']

    style A fill:#E1BEE7,stroke:#E1BEE7
    style B fill:#E1BEE7,stroke:#E1BEE7
    style C stroke:#E1BEE7,fill:#E1BEE7
    style D stroke:#FFE0B2,fill:#FFE0B2
    style E stroke:#FFE0B2,fill:#FFE0B2
