#CQ2: What city is a facility in, and what state is that city in?

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX cco: <https://www.commoncoreontologies.org/> 
PREFIX obo: <http://purl.obolibrary.org/obo/> 
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?facility ?facilityLabel ?city ?cityLabel ?state ?stateLabel
WHERE {
  ?facility rdf:type cco:ont00000192 ;
            rdfs:label ?facilityLabel ;
            obo:BFO_0000171 ?city .
  ?city rdfs:label ?cityLabel ;
        obo:BFO_0000171 ?state .
  ?state rdfs:label ?stateLabel .
  FILTER(?facilityLabel = "Empire State Building")
}
